# Generated by Django 3.2.4 on 2021-06-23 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('latitude', models.CharField(max_length=200)),
                ('longitude', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('connection_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=200)),
                ('friend_id', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantTrail',
            fields=[
                ('visit_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=200)),
                ('restaurant_id', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('latitude', models.CharField(max_length=200)),
                ('longitude', models.CharField(max_length=200)),
                ('image_url', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('zipcode', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=200)),
                ('review_id', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=200)),
                ('restaurant_id', models.CharField(max_length=200)),
                ('rating', models.IntegerField(max_length=1)),
                ('review', models.CharField(max_length=200)),
                ('recommended_dishes', models.CharField(max_length=200)),
                ('food_image', models.CharField(max_length=200)),
            ],
        ),
    ]
