# Generated by Django 3.2.4 on 2021-06-23 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodConnect', '0004_alter_friends_friend_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='user_id',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
