# Generated by Django 3.2.4 on 2021-06-23 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodConnect', '0006_alter_customer_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='user_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
