# Generated by Django 3.2.4 on 2021-06-23 09:37

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('foodConnect', '0008_alter_customer_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friends',
            name='connection_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='restauranttrail',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodConnect.customer'),
        ),
        migrations.AlterField(
            model_name='restauranttrail',
            name='visit_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='restaurant_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodConnect.restauranttrail'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='review_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodConnect.customer'),
        ),
    ]
