# Generated by Django 3.2.4 on 2021-06-23 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodConnect', '0010_remove_restauranttrail_review_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='food_image',
        ),
        migrations.CreateModel(
            name='ReviewImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagesUrl', models.CharField(max_length=200)),
                ('review_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodConnect.reviews')),
            ],
        ),
    ]
