# Generated by Django 3.2.4 on 2021-06-28 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodConnect', '0011_auto_20210623_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='image',
            field=models.CharField(default='', max_length=500),
        ),
    ]
